.catalog:
  name: "PostgreSQL"
  version: "9.4-11"
  description: "Lightweight and fast Server"
  uuid: postgresql-9.4-11-0
  minimum_rancher_version: v0.56.0
  questions: 
    - variable: "DATADIR"
      label: "Data Directory"
      description: "Set the Data Directory where PostgreSQL will store it's data. Best to have this on shared storage."
      default: "/somedir:/var/lib/postgresql:rw"
      required: true
      type: "string"
postgresql:
  scale: 1