Jira:
  ports:
  - 8080:8080/tcp
  environment:
    X_PROXY_NAME: ${PROXYNAME}
    X_PROXY_PORT: ${PROXYPORT}
    X_PROXY_SCHEME: ${PROXYSCHEME}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: cptactionhank/atlassian-jira:7.1.8
  volumes:
  - ${DATADIR}
  stdin_open: true