elasticsearch:
  ports:
  - 9200:9200/tcp
  - 9300:9300/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: elasticsearch:2.3.4
  volumes:
  - ${DATADIR}
  stdin_open: true