.catalog:
  name: "NGinX"
  version: "1.11.1"
  description: "Lightweight and fast Server"
  uuid: nginx-1.11.1-0
  minimum_rancher_version: v0.56.0
  questions: 
    - variable: "DATADIR"
      label: "Data Directory"
      description: "Set the Data Directory where confluence will store it's data. Best to have this on shared storage."
      default: "/somedir/:/usr/share/nginx/html"
      required: true
      type: "string"
    - variable: "VHOSTNAME"
      label: "Hostname"
      description: "Set the hostname of this server e.g www.somedomain.com"
      required: true
      default: "www.somedomain.com"
      type: "string"
nginx:
  scale: 1